global:
  name: LF AI & Data Interactive Landscape
  short_name: LFAI
  repo: lfai/lfai-landscape
  website: https://landscape.lfai.foundation
  short_domain: l.lfai.foundation
  company_url: https://lfai.foundation
  email: info@lfaidata.foundation
  membership: LF AI & Data Member Company
  self: https://www.crunchbase.com/organization/lf-artificial-intelligence-foundation
  slack_channel: T08PSQ7BQ/BEC09SE3V/3xuzW9rz4RQog9g9iUhnSxgI
  meta:
    title: LF AI & Data Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@LFAIDataFdn'
    google_site_verification: x3QPMhFwxg1ZMS9tlhhgwIJKokbEkt1zByMLMXiqnds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    companies: LF AI & Data Member Company
twitter:
  search: landscape.lfai.foundation
  url: https://landscape.lfai.foundation
  text: LF AI & Data Landscape from @LFAIDataFdn
relation:
  label: LF AI & Data Relation
  url: lfai
  values:
    - id: hosted
      label: LF AI & Data Projects
      children:
        - id: graduated
          label: Graduated LF AI & Data Projects
          prefix: LF AI
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Graduated
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: Incubating LF AI & Data Projects
          prefix: LF AI
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: Incubating
          big_picture_color: rgb(83, 113, 189)
        - id: sandbox
          label: Sandbox LF AI & Data Projects
          prefix: LF AI
          tag: Sandbox
          color: '#00cbff'
          big_picture_order: 3
          big_picture_label: Sandbox
          big_picture_color: rgb(108, 165, 209)
    - id: company
      label: LF AI & Data Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LF AI & Data Member Products/Projects
      tag: LFAI Member
    - id: false
      label: Non-LF AI & Data Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: LF AI & Data
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: LF AI & Data
    label: Member
    funding: General
    is_large: true
  Associate:
    name: LF AI & Data
    label: Member
    funding: Associate
    is_large: true
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF AI & Data Foundation Interactive Landscape</h1> The LF AI & Data Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a
    target="_blank" href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF
    landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccnceu20
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Linux Foundation AI & Data Landscape
    fullscreen_header: See the interactive landscape at l.lfaidata.foundation
    elements:
      - type: HorizontalCategory
        category: Machine Learning
        rows: 4
        width: 525
        height: 190
        top: 0
        left: 0
        color: rgb(4,81,49)
        fit_width: true
      - type: HorizontalCategory
        category: Deep Learning
        rows: 4
        width: 505
        height: 190
        top: 0
        left: 545
        color: rgb(7,136,62)
        fit_width: true
      - type: HorizontalCategory
        category: Reinforcement Learning
        rows: 4
        width: 165
        height: 190
        top: 0
        left: 1070
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Programming
        rows: 4
        width: 295
        height: 190
        top: 0
        left: 1255
        color: rgb(87,43,10)
        fit_width: true
      - type: HorizontalCategory
        category: Data
        rows: 4
        width: 1550
        height: 190
        top: 220     
        left: 0
        color: rgb(193,83,21)
        fit_width: true
      - type: HorizontalCategory
        category: Model
        rows: 4
        width: 1080
        height: 190
        top: 440
        left: 0
        color: rgb(37,81,209)
        fit_width: true
      - type: HorizontalCategory
        category: Trusted & Responsible AI
        rows: 3
        width: 450
        height: 190
        top: 440
        left: 1100
        color: rgb(111,12,52)
        fit_width: true
      - type: HorizontalCategory
        category: Distributed Computing
        rows: 4
        width: 415
        height: 190
        top: 660
        left: 0
        color: rgb(179,60,133)
        fit_width: true
      - type: LandscapeInfo
        width: 325
        height: 190
        top: 660
        left: 435
        children:
          - type: text
            text: |
              The LF AI & Data landscape explores open source projects in Artificial Intelligence and Data and their respective sub-domains.
            top: 25
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 20
            left: 5
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.lfaidata.foundation
            top: 109
            left: 9
            font_size: 9
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 25
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 65
            title: LF AI Logo
      - type: HorizontalCategory
        category: Security & Privacy
        rows: 4
        width: 130
        height: 190
        top: 660
        left: 780
        color: rgb(165,9,77)
        fit_width: true
      - type: HorizontalCategory
        category: Natural Language Processing
        rows: 4
        width: 400
        height: 190
        top: 660
        left: 930
        color: rgb(29,119,164)
        fit_width: true
      - type: HorizontalCategory
        category: Notebook Environment
        rows: 4
        width: 200
        height: 190
        top: 660
        left: 1350
        color: rgb(106,44,218)
        fit_width: true
  third:
    tab_index: 1
    url: members
    name: LF AI & Data Members
    title: LF AI & Data Member Company
    fullscreen_header: Become an LF AI & Data member at lfaidata.foundation/join
    elements:
      - type: HorizontalCategory
        category: Premier
        width: 700
        height: 180
        top: 0
        left: 0
        color: '#e5e4e2'
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: General
        width: 700
        height: 270
        top: 175
        left: 0
        color: '#d4af37'
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Associate
        cols: 30
        width: 700
        height: 270
        top: 440
        left: 0
        color: '#C0C0C0'
        fit_width: true
        is_large: true
    category: LF AI & Data Member Company
  fourth:
    tab_index: 2
    url: hosting
    name: Companies Hosting Projects
    title: Companies Hosting Projects
    fullscreen_header: Companies hosting projects in LF AI & Data
    elements:
      - type: HorizontalCategory
        category: Hosting Companies
        width: 750
        height: 300
        top: 0
        left: 0
        color: '#e5e4e2'
        fit_width: true
        is_large: true
    category: Hosting Companies
test:
  header: LF AI & Data Foundation Interactive Landscape
  section: Graduated LF AI & Data Projects
  logo: acumos.svg
prerender:
  members: /card-mode?category=lf-ai-data-member-company&grouping=category&embed=yes&style=borderless
