global:
  name: LF AI Interactive Landscape
  short_name: LFAI
  repo: lfai/lfai-landscape
  website: 'https://landscape.lfai.foundation'
  short_domain: l.lfai.foundation
  company_url: 'https://lfai.foundation'
  email: info@lfai.foundation
  membership: LF AI Member Company
  slack_channel: T08PSQ7BQ/BEC09SE3V/3xuzW9rz4RQog9g9iUhnSxgI
  meta:
    title: LF AI Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@LFAI_Foundation'
    google_site_verification: x3QPMhFwxg1ZMS9tlhhgwIJKokbEkt1zByMLMXiqnds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    cncf_sandbox: false
    companies: LF AI Member Company
twitter:
  search: landscape.lfai.foundation
  url: 'https://landscape.lfai.foundation'
  text: LF AI Landscape from @LFAI_Foundation
relation:
  label: LFAI Relation
  url: lfai
  values:
    - id: hosted
      label: LFAI Projects
      children:
        - id: graduated
          label: Graduated LFAI Projects
          prefix: LF AI
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LFAI Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating LFAI Projects
          prefix: LF AI
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: LFAI Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: LFAI Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LFAI Member Products/Projects
      tag: LFAI Member
    - id: false
      label: Non-LFAI Member Products/Projects
      url: 'no'
membership:
  Premium:
    name: LFAI
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: LFAI
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF AI Foundation Interactive Landscape</h1> The LF AI Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccncna19'
    image: /images/info1.jpg
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Linux Foundation AI Landscape
    fullscreen_header: See the interactive landscape at l.lfai.foundation
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1115
      height: 770
    fullscreen_size:
      width: 1155
      height: 840
    elements:
      - type: HorizontalCategory
        category: Machine Learning
        rows: 3
        width: 380
        height: 160
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
        fit_width: true
      - type: HorizontalCategory
        category: Deep Learning
        rows: 3
        width: 425
        height: 160
        top: 0
        left: 400
        color: 'rgb(104, 145, 145)'
        fit_width: true
      - type: HorizontalCategory
        category: Notebook Environment
        rows: 3
        width: 125
        height: 160
        top: 0
        left: 845
        color: 'rgb(43, 142, 136)'
        fit_width: true
      - type: HorizontalCategory
        category: Reinforcement Learning
        rows: 4
        width: 125
        height: 160
        top: 0
        left: 990
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Distributed Computing
        rows: 3
        width: 300
        height: 160
        top: 190
        left: 0
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Data
        rows: 3
        width: 795
        height: 160
        top: 190
        left: 320
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: AI Ethics & Fairness
        rows: 4
        width: 155
        height: 160
        top: 380
        left: 0
        color: 'rgb(142, 209, 216)'
        fit_width: true
      - type: HorizontalCategory
        category: Natural Language Processing
        rows: 4
        width: 200
        height: 160
        top: 380
        left: 175
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Model
        rows: 4
        width: 720
        height: 160
        top: 380
        left: 395
        color: 'rgb(108, 135, 75)'
        fit_width: true
      - type: HorizontalCategory
        category: LF AI Member Company
        rows: 3
        width: 675
        height: 160
        top: 570
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: LandscapeInfo
        width: 420
        height: 160
        top: 570
        left: 700
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore open source artificial intelligence (AI), machine learning (ML), and deep learning (DL) projects,
              and lists the members of the LF AI Foundation.
            top: 15
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.lfai.foundation
            top: 99
            left: 9
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 15
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 55
test:
  header: LF AI Foundation Interactive Landscape
  section: Graduated LFAI Projects
  logo: acumos.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
