global:
  name: LF DL Interactive Landscape
  short_name: LFDL
  repo: LFDLFoundation/lfdl-landscape
  website: 'https://landscape.lfdl.io'
  short_domain: l.lfdl.io
  company_url: 'https://lfdl.io'
  email: info@lfdl.io
  meta:
    title: LF DL Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@LFDeepLearning'
    google_site_verification: GOaZHK1WLPDcnST1L70tMMWe3qNr_idDogl5SryoJq8
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    cncf_sandbox: false
    companies: LF DL Member Company
twitter:
  search: landscape.lfdl.io
  url: 'https://landscape.lfdl.io'
  text: LF Deep Learning Landscape from @LFDeepLearning
relation:
  label: LFDL Relation
  url: lfdl
  values:
    - id: hosted
      label: LFDL Projects
      children:
        - id: graduated
          label: Graduated LFDL Projects
          prefix: LF DL
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LFDL Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating LFDL Projects
          prefix: LF DL
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: LFDL Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: LFDL Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LFDL Member Products/Projects
      tag: LFDL Member
    - id: false
      label: Non-LFDL Member Products/Projects
      url: 'no'
membership:
  premier:
    name: LFDL
    label: Premier Member
    funding: Premier
  general:
    name: LFDL
    label: Member
    funding: General
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Deep Learning Foundation Interactive Landscape</h1> The LF Deep Learning Foundation landscape (<a target="_blank"
    href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a
    href="http://landscape.cncf.io">CNCF landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccnceu19'
    image: /images/info0.jpg
  - url: 'https://events.linuxfoundation.cn/events/kubecon-cloudnativecon-china-2019/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccncch19'
    image: /images/info1.jpg
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Linux Foundation Deep Learning Landscape
    fullscreen_header: See the interactive landscape at l.lfdl.io
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1115
      height: 730
    fullscreen_size:
      width: 1155
      height: 800
    elements:
      - type: HorizontalCategory
        category: Machine Learning
        rows: 3
        width: 380
        height: 160
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
        fit_width: true
      - type: HorizontalCategory
        category: Deep Learning
        rows: 3
        width: 425
        height: 160
        top: 0
        left: 400
        color: 'rgb(104, 145, 145)'
        fit_width: true
      - type: HorizontalCategory
        category: Notebook Environment
        rows: 3
        width: 125
        height: 160
        top: 0
        left: 845
        color: 'rgb(43, 142, 136)'
        fit_width: true
      - type: HorizontalCategory
        category: Reinforcement Learning
        rows: 4
        width: 125
        height: 160
        top: 0
        left: 990
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Data
        rows: 3
        width: 705
        height: 160
        top: 190
        left: 410
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: AI Ethics & Fairness
        rows: 4
        width: 125
        height: 160
        top: 380
        left: 0
        color: 'rgb(142, 209, 216)'
        fit_width: true
      - type: HorizontalCategory
        category: Natural Language Processing
        rows: 3
        width: 155
        height: 160
        top: 380
        left: 145
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Model
        rows: 3
        width: 795
        height: 160
        top: 380
        left: 320
        color: 'rgb(108, 135, 75)'
        fit_width: true
      - type: HorizontalCategory
        category: LF DL Member Company
        rows: 4
        width: 850
        height: 160
        top: 570
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Distributed Computing
        rows: 4
        width: 245
        height: 160
        top: 570
        left: 870
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: LandscapeInfo
        width: 390
        height: 160
        top: 190
        left: 5
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore open source artificial intelligence (AI), machine learning (ML), and deep learning (DL) projects,
              and also shows the member companies of the LF Deep Learning Foundation.
            top: 20
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 15
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.lfdl.io
            top: 104
            left: 19
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 20
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 60
test:
  header: LF Deep Learning Foundation Interactive Landscape
  section: Graduated LFDL Projects
  logo: acumos.svg
update_server:
  ip: 147.75.39.153
  update_hour: 0
  update_minute: 30
